const data = {
    products: [
        {
            _id:'1',
            name : 'Platano de seda',
            category:'fruta',
            image:'/images/platano.jpg',
            price : 4.5,
            countInStock:5,
            numReviews : 'Fruta' , 
            description:'platano de seda sin gluten' ,
        },
        {
            _id:'2',
            name : 'Platano de seda',
            category:'fruta',
            image:'/images/lenteja.jpg',
            price : 4.5,
            countInStock:5,
            numReviews : 'Fruta', 
            description:'platano de seda sin gluten' ,
        },
        {
            _id:'3',
            name : 'Lenteja Paisana',
            category:'Legumbre',
            image:'/images/platano.jpg',
            price : 4.5,
            countInStock:0,
            numReviews : 'Legumbre', 
            description:'platano de seda sin gluten' ,
        },
             {
            _id:'4',
            name : 'Lenteja Paisana',
            category:'Legumbre',
            image:'/images/platano.jpg',
            price : 4.5,
            countInStock:10,
            numReviews : 'Legumbre', 
            description:'platano de seda sin gluten' ,
        },
        {
            _id:'5',
            name : 'Lenteja Paisana',
            category:'Legumbre',
            image:'/images/platano.jpg',
            price : 4.5,
            countInStock:0,
            numReviews : 'Legumbre', 
            description:'platano de seda sin gluten' ,
        },
        {
            _id:'6',
            name : 'Lenteja Paisana',
            category:'Legumbre',
            image:'/images/platano.jpg',
            price : 4.5,
            countInStock:0,
            numReviews : 'Legumbre', 
            description:'platano de seda sin gluten' ,
        },

    ],
};
export default data;